(import (scheme write)
        (scheme base)
        (prefix (advent day1) day1/)
        (prefix (advent day2) day2/)
        (prefix (advent day3) day3/)
        )

; (day1/main)
; (day2/main)
(day3/main)
